/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import Controller.LoginController;
import com.raven.component.Bottom;
import com.raven.main.Main;
import com.raven.swing.MImage;
import java.awt.Color;
import java.awt.Frame;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class DangNhapPnl extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapPnl
     */
    int xy, xx;
    private Bottom bottom = new Bottom();
    private LoginController loginController;

    public void setController(LoginController mainFrameController) {
        this.loginController = mainFrameController;
    }

    public DangNhapPnl() {
        initComponents();
        loginController = new LoginController(this);
        errorLb.setText("");

        txtTk.setText("admin");
        txtMk.setText("admin");
        this.icon2.setVisible(false);
        this.setIconImage(MImage.getAppIcon());

    }

    public static String tenDangNhap = "";
    public static int level = 0;
    public static int ID = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        kGradientPanel1 = new com.raven.swing.KGradientPanel();
        txtMk = new javax.swing.JPasswordField();
        kButton11 = new com.raven.swing.KButton1();
        kButton12 = new com.raven.swing.KButton1();
        errorLb = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        kGradientPanel1.setkEndColor(new java.awt.Color(51, 153, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 153, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMk.setBackground(new Color(0,0,0,0));
        txtMk.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        txtMk.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMk.setCaretColor(new java.awt.Color(204, 0, 255));
        kGradientPanel1.add(txtMk, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 299, 30));

        kButton11.setText("Exit");
        kButton11.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        kButton11.setkBorderRadius(40);
        kButton11.setkFillButton(false);
        kButton11.setkHoverForeGround(new java.awt.Color(0, 0, 204));
        kButton11.setkHoverStartColor(new java.awt.Color(0, 0, 204));
        kButton11.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton11.setMaximumSize(new java.awt.Dimension(75, 22));
        kButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton11ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 123, 35));

        kButton12.setText("Login");
        kButton12.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        kButton12.setkBorderRadius(40);
        kButton12.setkFillButton(false);
        kButton12.setkHoverForeGround(new java.awt.Color(0, 0, 204));
        kButton12.setkHoverStartColor(new java.awt.Color(0, 0, 204));
        kButton12.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton12.setMaximumSize(new java.awt.Dimension(75, 22));
        kButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton12ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 123, 35));

        errorLb.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorLb.setForeground(new java.awt.Color(255, 0, 0));
        errorLb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        kGradientPanel1.add(errorLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 258, 24));

        jLabel4.setFont(new java.awt.Font("UTM Avo", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        txtTk.setBackground(new Color(0,0,0,0));
        txtTk.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        txtTk.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtTk.setCaretColor(new java.awt.Color(204, 0, 255));
        kGradientPanel1.add(txtTk, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 320, 30));

        jLabel5.setFont(new java.awt.Font("UTM Avo", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Passworld");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/shop-16.png"))); // NOI18N
        jLabel1.setText("Dũng Phát");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/shop-32.png"))); // NOI18N
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 40, 38));

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/eye.png"))); // NOI18N
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon1MousePressed(evt);
            }
        });
        kGradientPanel1.add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, 37));

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/invisible.png"))); // NOI18N
        icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon2MousePressed(evt);
            }
        });
        kGradientPanel1.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, 37));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void kButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton11ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_kButton11ActionPerformed

    private void kButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton12ActionPerformed
        // TODO add your handling code here:
        String tk = txtTk.getText();
        String mk = String.valueOf(txtMk.getPassword());
        tenDangNhap = loginController.showName(tk, mk);
        level = loginController.showLevel(tk, mk);
        ID = loginController.showID(tk, mk);

        if (loginController.kiemTra(tk, mk)) {
            try {
                Main main = new Main();
                System.out.println(loginController.showName(tk, mk));
                main.setVisible(true);
                this.dispose();
            } catch (ParseException ex) {
                Logger.getLogger(DangNhapPnl.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            errorLb.setText("Sai tên đăng nhập hoặc mật khẩu ! ");
        }
    }//GEN-LAST:event_kButton12ActionPerformed

    private void icon1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MousePressed
        // TODO add your handling code here:
        icon2.setVisible(true);
        icon1.setVisible(false);
        txtMk.setEchoChar((char) '*');
    }//GEN-LAST:event_icon1MousePressed

    private void icon2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MousePressed
        // TODO add your handling code here:

        icon1.setVisible(true);
        icon2.setVisible(false);
        txtMk.setEchoChar((char) 0);
    }//GEN-LAST:event_icon2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapPnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapPnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapPnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapPnl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapPnl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLb;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private com.raven.swing.KButton1 kButton11;
    private com.raven.swing.KButton1 kButton12;
    private com.raven.swing.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField txtMk;
    private javax.swing.JTextField txtTk;
    // End of variables declaration//GEN-END:variables
}
